<script>
    import { onDestroy } from "svelte";
    import Yoda from "$lib/ethereum/yoda.png";
    import { wallet } from "../../stores/wallet";

    export let address = "0x";
    let shortAddress;

    function shorten(address) {
        let shortAddress = "";
        return shortAddress.concat(
            address.slice(0, 7),
            "...",
            address.slice(-5)
        );
    }

    $: shortAddress = shorten(address);

    const unsubscribe = wallet.subscribe((value) => {
        address = value[0];
    });

    onDestroy(() => {
        unsubscribe();
    });
</script>

<div class="wallet">
    <img class="wallet-icon" src="https://avatars.dicebear.com/api/jdenticon/{address}.svg" alt="Autogenerated wallet icon" />
    <div class="content">
        <p class="address">{shortAddress}</p>
        <p class="info">Wallet</p>
    </div>
</div>

<style>
    .wallet {
        display: inline-flex;
        flex-direction: row;
        padding: 0.5em;
        align-items: flex-start;
    }

    .wallet-icon {
        margin-right: 0.5em;
        align-self: center;
        height: 2em;
        width: 2em;
    }

    .content {
        display: flex;
        flex-direction: column;
        align-self: center;
    }

    p {
        display: inline;
        color: var(--text-color-white);
        margin: 0;
        line-height: 16px;
    }

    .address {
        font-size: 14px;
    }

    .info {
        opacity: 0.6;
        font-size: 12px;
    }
</style>
